/*

better_trackpad.h - Library to simplify and improve trackpad input on windows

To use this library, 
```
#define BT_IMPLEMENTATION 
```  
before including the header file in one of your c files.

To use this library:
    - Create a `bt_context`
    - Call `bt_init`, optionally check `has_trackpad` and/or `initialized`
    - Upon receiving a `WM_INPUT` message, call `bt_process_input`
    - Somewhere in your main application loop, call `bt_passive_update`
    - Call `bt_destroy` (if you are using malloc/free)

This library generates three types of messages:
    1) `BT_MSG_RAW` - Essentially the raw contact information, unprocessed
    2) `BT_MSG_CONTACT_*` - These will track contacts, giving enter, update,
        and exit messages separately
    3) `BT_MSG_GESTURE_*` - Higher level gestures

Each type of message can be selectively disabled during initialization.

You can also directly look at the members `num_contacts` and `contacts` in 
the `bt_context` directly for a polling style input system.

Note about gestures:
    - I would generally not recommend using `BT_MSG_GESTURE_PAN` messages
        because they do not incorporate system preferences about scrolling
        speed and/or direction
    - I have not found a good way to distinguish true `WM_MOUSEWHEEL` messages
        where the user is physically pressing control, and synthetic events 
        generated by the trackpad zoom gesture, but you can always look at the
        `gesture_state` member of the context to see if better_trackpad detects
        and zoom event and proceed accordingly in the mouse wheel message

Coordinate System:
    - Trackpads give a logical min and max in each axis, as well as a physical
        min and max
    - better_trackpad converts the physical measure into millimeters
    - See the `(x/y)_(min/max)_(logical/mm)` members in the context
    - +x is right, +y is toward the user

Memory Allocation:
    - better_trackpad supports two styles of memory allocation
        - malloc/free
        - arenas
    - To customize the malloc/free style, define `BT_MALLOC` and `BT_FREE`
    - For the arenas, define `BT_USE_ARENAS`.
        - Then, you are *required* to define `BT_ARENA`, `BT_ARENA_GET_POS`,
        `BT_ARENA_PUSH`, and `BT_ARENA_POP_TO`
    - Only `bt_init` allocates memory

Error Handling:
    - The most important thing is checking if the initialization failed,
        which can be done by checking the `initialized` member in the context
    - better_trackpad passively records errors in the `err_str` member 
        of the context
    - Error strings can be disabled with:
        `#define BT_ERROR_STRINGS 0`
    - Even if error strings are disabled, a non-NULL pointer in `err_str` 
        indicates that an error occurred

Bug Reporting - If this library does not work for you, plaese let me know on
GitHub, but include the following in your issue:
    1) `#define BT_DEBUG_INFO` This will print *a lot* of debug info about your
        device, and should help diagnose the issue
    2) The model of your laptop and/or trackpad

Note on Linking
    - better_trackpad requires `hid.lib` to work
    - By default, there is a pragma comment, but this can be disabled with
        `#define BT_NO_LIB_COMMENT`

For any other features, just refer to the comment above their definition. You 
only need to look at the stuff before the `#ifdef BT_IMPLEMENTATION`.

*/

#ifndef __BT_HEADER__
#define __BT_HEADER__

#include <hidclass.h>
#include <hidsdi.h>
#include <hidpi.h>

#ifndef BT_NO_LIB_COMMENT
#   pragma comment(lib, "hid")
#endif

#ifndef BT_MAX_CONTACTS
#   define BT_MAX_CONTACTS 10
#endif

#if BT_MAX_CONTACTS < 2
#error BT_MAX_CONTACTS should be at least two
#endif

#ifndef BT_MSG_ID_OFFSET
#   define BT_MSG_ID_OFFSET 1
#endif

// This message essentially passes on the unprocessed
// result of the associated WM_INPUT message
// wParam stores the associated `bt_sample` (use BT_SAMPLE_WPARAM)
// lParam stores the associated `bt_contact` (use BT_CONTACT_LPARAM)
#define BT_MSG_RAW (WM_APP + BT_MSG_ID_OFFSET + 0)

// Sent upon first detecting a contact
// lParam stores the associated `bt_contact` (use BT_CONTACT_LPARAM)
#define BT_MSG_CONTACT_ENTER (WM_APP + BT_MSG_ID_OFFSET + 1)

// Sent when a contact moves, filtering out repeated positions
// lParam stores the associated `bt_contact` (use BT_CONTACT_LPARAM)
#define BT_MSG_CONTACT_UPDATE (WM_APP + BT_MSG_ID_OFFSET + 2)

// Sent when a contact is detected as leaving
// `bt_passive_update` is required for this
// They are also sent from `bt_process_input` if that detects it
// lParam stores the associated `bt_contact` (use BT_CONTACT_LPARAM)
#define BT_MSG_CONTACT_EXIT (WM_APP + BT_MSG_ID_OFFSET + 3)

// Sent when a two-finger pan gesture is detected
// I would recommend against using this as it does not incorporate system
// settings about zoom speed and direction, and it does not work with more
// than two contacts (by design). I am doing the gesture recognition 
// regardless, so I figured I might as well expose it
// wParam stores an associated `bt_sample` (use BT_SAMPLE_WPARAM)
// lParam stores the associated `bt_gesture_pan` (use BT_GESTURE_PAN_LPARAM)
#define BT_MSG_GESTURE_PAN (WM_APP + BT_MSG_ID_OFFSET + 4)

// Sent when a two-finger zoom gesture is detected
// wParam stores an associated `bt_sample` (use BT_SAMPLE_WPARAM)
// lParam stores the associated `bt_gesture_zoom` (use BT_GESTURE_ZOOM_LPARAM)
#define BT_MSG_GESTURE_ZOOM (WM_APP + BT_MSG_ID_OFFSET + 5)

#if defined(BT_USE_ARENAS)
#   if !defined(BT_ARENA) || !defined(BT_ARENA_GET_POS) || \
        !defined(BT_ARENA_PUSH) || !defined(BT_ARENA_POP_TO)
#       error Missing definition for arena implementation
#   endif
#else // !defined(BT_USE_ARENAS)
#   ifndef BT_MALLOC
#       define BT_MALLOC malloc
#   endif
#   ifndef BT_FREE
#       define BT_FREE free
#   endif
#endif

#ifndef BT_ERROR_STRINGS
#   define BT_ERROR_STRINGS 1
#endif

#if BT_ERROR_STRINGS
#   define _BT_ERROR(s) (s)
#else
#   define _BT_ERROR(s) (char*)(-1)
#endif

#include <stdint.h>

typedef int8_t bt_i8;
typedef int16_t bt_i16;
typedef int32_t bt_i32;
typedef int64_t bt_i64;
typedef uint8_t bt_u8;
typedef uint16_t bt_u16;
typedef uint32_t bt_u32;
typedef uint64_t bt_u64;

typedef float bt_f32;

typedef enum {
    BT_EXP_P_0 = 0x0,
    BT_EXP_P_1 = 0x1,
    BT_EXP_P_2 = 0x2,
    BT_EXP_P_3 = 0x3,
    BT_EXP_P_4 = 0x4,
    BT_EXP_P_5 = 0x5,
    BT_EXP_P_6 = 0x6,
    BT_EXP_P_7 = 0x7,
    BT_EXP_N_8 = 0x8,
    BT_EXP_N_7 = 0x9,
    BT_EXP_N_6 = 0xa,
    BT_EXP_N_5 = 0xb,
    BT_EXP_N_4 = 0xc,
    BT_EXP_N_3 = 0xd,
    BT_EXP_N_2 = 0xe,
    BT_EXP_N_1 = 0xf,
} bt_unit_exp;

// 10^(Unit Exp) multipliers
// Used to convert to and from different units
extern const bt_f32 bt_exp_multipliers[16];

typedef struct {
    // Receive input even when window is not in foreground
    bt_u32 input_sink: 1;
    // Disables the sending of BT_MSG_RAW messages
    bt_u32 disable_raw_msgs: 1;
    // Disables the sending of BT_MSG_CONTACT_* messages
    bt_u32 disable_contact_msgs: 1;
    // Disables the sending of BT_MSG_ZOOM messages
    bt_u32 disable_gesture_msgs: 1;
} bt_context_flags;

typedef struct {
    HWND hwnd;
    // Defaults to 16ms (set it to 1 to get the minimum timeout)
    bt_u64 exit_timeout_us;
    // Defaults to 2 mm
    bt_f32 pan_deadzone_mm;
    // Defaults to 12 mm
    bt_f32 zoom_deadzone_mm;
    bt_context_flags flags;
} bt_context_desc;

// Per-contact info
// Gotten from lParam
typedef struct {
    // USB HID Usage Page 0x01, Usage 0x30
    bt_i16 x;
    // USB HID Usage Page 0x01, Usage 0x31
    bt_i16 y;
    // USB HID Usage Page 0x0d, Usage 0x51
    bt_i16 id;
} bt_contact;

#define BT_CONTACT_LPARAM(lParam) (bt_contact){ \
    .x  = (bt_i16)(((bt_u64)(lParam) >>  0) & 0xffff), \
    .y  = (bt_i16)(((bt_u64)(lParam) >> 16) & 0xffff), \
    .id = (bt_i16)(((bt_u64)(lParam) >> 32) & 0xffff), \
}

// Per-sample info (shared between multiple contacts)
// Gotten from wParam
typedef struct {
    // USB HID Usage Page 0x0d, Usage 0x56
    // See bt_context.scan_time_exp for scientific exponent
    bt_u16 scan_time;
    // USB HID Usage Page 0x0d, Usage 0x54
    bt_u16 contact_count;
} bt_sample;

#define BT_SAMPLE_WPARAM(wParam) (bt_sample){ \
    .scan_time      = (bt_u16)(((bt_u64)(wParam) >>  0) & 0xffff), \
    .contact_count  = (bt_i16)(((bt_u64)(wParam) >> 16) & 0xffff), \
}

// Info for pan gesture
// Gotten from lParam
typedef union {
    struct {
        bt_f32 move_x;
        bt_f32 move_y;
    };
    bt_f32 velocity;

    bt_u64 bits;
} bt_gesture_pan;

#define BT_GESTURE_PAN_LPARAM(lParam) (bt_gesture_pan){ .bits = (bt_u64)(lParam) }

// Info for zoom gesture
// Gotten from lParam
typedef union {
    struct {
        // Distance when two contactcs were first detected
        // NOT when the zoom gesture was first detected
        bt_f32 start_dist;
        // Change in distance from previous zoom message
        bt_f32 dist_change;
    };

    bt_u64 bits;
} bt_gesture_zoom;

#define BT_GESTURE_ZOOM_LPARAM(lParam) (bt_gesture_zoom) { .bits = (bt_u64)(lParam) }

typedef enum {
    BT_GES_NONE = 0,
    BT_GES_UNDECIDED,
    BT_GES_PAN,
    BT_GES_ZOOM
} bt_gesture_state;

typedef struct {
    bt_context_flags flags;
    bt_u32 rawinput_size;
    
    HANDLE device_handle;
    PHIDP_PREPARSED_DATA ppd;
    RAWINPUT* rawinput;

    bt_u64 perf_freq;
    bt_u64 exit_timeout_us;
    bt_u64 prev_input_us;

    bt_u32 max_link_collections;
    bt_u32 num_link_collections;
    bt_u16* link_collections;

    bt_unit_exp scan_time_exp;

    bt_i16 x_min_logical;
    bt_i16 x_max_logical;
    bt_i16 y_min_logical;
    bt_i16 y_max_logical;

    bt_f32 x_min_mm;
    bt_f32 x_max_mm;
    bt_f32 y_min_mm;
    bt_f32 y_max_mm;

    // Deadzones in logical units
    bt_f32 pan_sqr_deadzone;
    bt_f32 zoom_sqr_deadzone;

    // Gesture start positions
    bt_i16 ges_start_x0;
    bt_i16 ges_start_y0;
    bt_i16 ges_start_x1;
    bt_i16 ges_start_y1;

    // Previous positions of gestures
    bt_i16 ges_prev_x0;
    bt_i16 ges_prev_y0;
    bt_i16 ges_prev_x1;
    bt_i16 ges_prev_y1;

    bt_u32 num_contacts;
    bt_contact contacts[BT_MAX_CONTACTS];

    char* err_str;

    bt_i8 has_trackpad;
    bt_i8 initialized;

    bt_u8 gesture_state;
} bt_context;

#ifdef BT_USE_ARENAS
void bt_init(BT_ARENA* arena, bt_context* context, const bt_context_desc* desc);
#else
void bt_init(bt_context* context, const bt_context_desc* desc);
#endif

// Call this upon recieving a WM_INPUT message
// Make sure to return DefWindowProc
void bt_process_input(
    bt_context* context, HWND hWnd, WPARAM wParam, LPARAM lParam
);

// This should be called one every frame (or similar)
// Required for certain higher-level messages
// Not necessary if you are just using the raw messages
void bt_passive_update(bt_context* context, HWND hWnd);

// This function will not stop the `WM_INPUT` messages, as they cannot be 
// stopped (I think). It will free all the memory allocated by the context. 
void bt_destroy(bt_context* context);

#endif // __BT_HEADER__

#ifdef BT_IMPLEMENTATION

//////////////////////////////////////////////////////////////////////////////
///                                                                        ///
///                             Implementation                             ///
///                                                                        ///
//////////////////////////////////////////////////////////////////////////////

#ifdef BT_DEBUG_INFO
#   include <stdio.h>
#endif

#include <stdlib.h>
#include <math.h>

#define _BT_ABS(x) ((x) < 0 ? (-(x)) : (x))

typedef struct {
    bt_i16 start_x;
    bt_i16 start_y;
    bt_i16 cur_x;
    bt_i16 cur_y;
} _bt_pan_info;

typedef struct {
    bt_u32 start_sqr_dist;
    bt_u32 cur_sqr_dist;
} _bt_zoom_info;

#define _BT_CONTACT_TO_LPARAM(contact) (\
    (((bt_u64)(contact).id) << 32) | \
    (((bt_u64)(contact).y)  << 16) | \
    (((bt_u64)(contact).x)  <<  0))

const bt_f32 bt_exp_multipliers[16] = {
    [BT_EXP_P_0] = 1e0f,
    [BT_EXP_P_1] = 1e1f,
    [BT_EXP_P_2] = 1e2f,
    [BT_EXP_P_3] = 1e3f,
    [BT_EXP_P_4] = 1e4f,
    [BT_EXP_P_5] = 1e5f,
    [BT_EXP_P_6] = 1e6f,
    [BT_EXP_P_7] = 1e7f,

    [BT_EXP_N_8] = 1e-8f,
    [BT_EXP_N_7] = 1e-7f,
    [BT_EXP_N_6] = 1e-6f,
    [BT_EXP_N_5] = 1e-5f,
    [BT_EXP_N_4] = 1e-4f,
    [BT_EXP_N_3] = 1e-3f,
    [BT_EXP_N_2] = 1e-2f,
    [BT_EXP_N_1] = 1e-1f,
};

static bt_i32 _bt_valid_value_cap(HIDP_VALUE_CAPS* value_cap);
static bt_i32 _bt_to_mm(bt_u16 units, bt_u16 units_exp, bt_f32* val);
static bt_u64 _bt_time_us(bt_context* context);
static bt_f32 _bt_sqr_dist(bt_i16 x0, bt_i16 y0, bt_i16 x1, bt_i16 y1);
static bt_f32 _bt_dist(bt_i16 x0, bt_i16 y0, bt_i16 x1, bt_i16 y1);

#ifdef BT_USE_ARENAS
#   define _BT_ALLOC(size) BT_ARENA_PUSH(arena, (size))
#else
#   define _BT_ALLOC(size) BT_MALLOC(size)
#endif

#ifdef BT_USE_ARENAS
void bt_init(BT_ARENA* arena, bt_context* context, const bt_context_desc* desc) {
#else
void bt_init(bt_context* context, const bt_context_desc* desc) {
#endif
    *context = (bt_context){ 0 };

#ifdef BT_USE_ARENAS
    bt_u64 init_pos = BT_ARENA_GET_POS(arena);
#endif

    context->flags = desc->flags;
    context->exit_timeout_us = desc->exit_timeout_us ? desc->exit_timeout_us : 16000;

    bt_u32 num_devices = 0;
    if (GetRawInputDeviceList(
        NULL, &num_devices, sizeof(RAWINPUTDEVICELIST)
    ) != 0) {
        context->err_str = _BT_ERROR("Failed to get device list size");
        return;
    }

    RAWINPUTDEVICELIST* devices = (RAWINPUTDEVICELIST*)_BT_ALLOC(
        num_devices * sizeof(RAWINPUTDEVICELIST)
    );

    if (GetRawInputDeviceList(
        devices, &num_devices, sizeof(RAWINPUTDEVICELIST)
    ) != num_devices) {
        context->err_str = _BT_ERROR("Failed to get device list");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(devices);
#endif

        return;
    }

    for (bt_u32 i = 0; i < num_devices; i++) {
        if (devices[i].dwType != RIM_TYPEHID) { continue; }

        bt_u32 device_info_size = sizeof(RID_DEVICE_INFO);
        RID_DEVICE_INFO device_info = { 0 };
        if (GetRawInputDeviceInfo(
                devices[i].hDevice, RIDI_DEVICEINFO,
                &device_info, &device_info_size
        ) != sizeof(RID_DEVICE_INFO)) {
            context->err_str = _BT_ERROR("Failed to get device info");

#ifdef BT_USE_ARENAS
            BT_ARENA_POP_TO(arena, init_pos);
#else
            BT_FREE(devices);
#endif

            return;
        }

        if (device_info.dwType != RIM_TYPEHID) { continue; }

        // Usage Page should be 0x0d (Digitizers)
        // Usage should be 0x05 (Touch Pads)
        if (
            device_info.hid.usUsagePage == 0x0d &&
            device_info.hid.usUsage == 0x05
        ) {
            context->device_handle = devices[i].hDevice;
            context->has_trackpad = 1;
            break;
        }
    }

#ifdef BT_USE_ARENAS
    BT_ARENA_POP_TO(arena, init_pos);
#else
    BT_FREE(devices);
#endif


    if (!context->has_trackpad) {
        context->initialized = 1;
        return;
    }

    LARGE_INTEGER perf_freq = { 0 };
    if (!QueryPerformanceFrequency(&perf_freq)) {
        context->err_str = _BT_ERROR("Failed to query performance frequency");
        return;
    }
    context->perf_freq = (bt_u64)perf_freq.QuadPart;

    RAWINPUTDEVICE rid = {
        .usUsagePage = 0x0d,
        .usUsage = 0x05,
        .dwFlags = 
            (desc->flags.input_sink * RIDEV_INPUTSINK),
        .hwndTarget = desc->hwnd
    };

    if (!RegisterRawInputDevices(&rid, 1, sizeof(RAWINPUTDEVICE))) {
        context->err_str =
            _BT_ERROR("Failed to register trackpad for raw input");
        return;
    }

    bt_u32 ppd_size = 0;
    if (GetRawInputDeviceInfo(
        context->device_handle, RIDI_PREPARSEDDATA, NULL, &ppd_size
    ) != 0) {
        context->err_str =
            _BT_ERROR("Failed to get trackpad preparsed data size");
        return;
    }

    context->ppd = (PHIDP_PREPARSED_DATA)_BT_ALLOC(ppd_size);
    if (GetRawInputDeviceInfo(
        context->device_handle, RIDI_PREPARSEDDATA, context->ppd, &ppd_size
    ) != ppd_size) {
        context->err_str = _BT_ERROR("Failed to get trackpad preparsed data");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(context->ppd);
#endif

        return;
    }

    // Note(Ian)
    // I feel like there should be a way to use the `InputReportByteLength`
    // field to statically initialize memory for the the `RAWINPUT` reports,
    // but I was not able to figure out if there is a direct relationship
    // between that value and the size of the `RAWINPUT`
    HIDP_CAPS caps = { 0 };
    if (
        HidP_GetCaps(context->ppd, &caps) != HIDP_STATUS_SUCCESS ||
        caps.UsagePage != 0x0d || caps.Usage != 0x05
    ) {
        context->err_str = _BT_ERROR("Failed to get device capabilities");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(context->ppd);
#endif

        return;
    }

    context->max_link_collections = caps.NumberLinkCollectionNodes;
    context->link_collections = (bt_u16*)_BT_ALLOC(
        sizeof(bt_u16) * context->max_link_collections
    );

    // This should always be greater than the necessary memory because RAWHID
    // techincally includes a one-byte array instead of a flexible array member
    // which causes the 
    context->rawinput_size = sizeof(RAWINPUTHEADER) +
        sizeof(RAWHID) + caps.InputReportByteLength;
    context->rawinput = (RAWINPUT*)_BT_ALLOC(context->rawinput_size);

#if defined(BT_DEBUG_INFO)
    printf(
        "Device Capabilities: {\n"
        "    Usage                     = 0x%02x,\n"
        "    UsagePage                 = 0x%02x,\n"
        "    InputReportByteLength     = %u,\n"
        "    FeatureReportByteLength   = %u,\n"
        "    NumberLinkCollectionNodes = %u,\n"
        "    NumberInputButtonCaps     = %u,\n"
        "    NumberInputValueCaps      = %u,\n"
        "    NumberInputDataIndices    = %u,\n"
        "    NumberFeatureButtonCaps   = %u,\n"
        "    NumberFeatureValueCaps    = %u,\n"
        "    NumberFeatureDataIndices  = %u\n"
        "}\n",
        caps.Usage,
        caps.UsagePage,
        caps.InputReportByteLength,
        caps.FeatureReportByteLength,
        caps.NumberLinkCollectionNodes,
        caps.NumberInputButtonCaps,
        caps.NumberInputValueCaps,
        caps.NumberInputDataIndices,
        caps.NumberFeatureButtonCaps,
        caps.NumberFeatureValueCaps,
        caps.NumberFeatureDataIndices
    );
#endif

#ifdef BT_USE_ARENAS
    bt_u64 pre_value_caps_pos = BT_ARENA_GET_POS(arena);
#endif

    HIDP_VALUE_CAPS* value_caps = (HIDP_VALUE_CAPS*)_BT_ALLOC(
        sizeof(HIDP_VALUE_CAPS) * caps.NumberInputValueCaps
    );
    bt_u16 num_value_caps = caps.NumberInputValueCaps;

    if (
        HidP_GetValueCaps(
            HidP_Input, value_caps, &num_value_caps, context->ppd
        ) != HIDP_STATUS_SUCCESS || num_value_caps != caps.NumberInputValueCaps
    ) {
        context->err_str = _BT_ERROR("Failed to get value capabilities");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(value_caps);
        BT_FREE(context->link_collections);
        BT_FREE(context->rawinput);
        BT_FREE(context->ppd);
#endif

        return;
    }

#if defined(BT_DEBUG_INFO)
    for (bt_u16 i = 0; i < num_value_caps; i++) {
        printf(
            "Value Capabilities: {\n"
            "    UsagePage         = 0x%02x,\n"
            "    ReportID          = %u,\n"
            "    IsAlias           = %u,\n"
            "    BitField          = %u,\n"
            "    LinkCollection    = %u,\n"
            "    LinkUsage         = 0x%02x,\n"
            "    LinkUsagePage     = 0x%02x,\n"
            "    IsRange           = %u,\n"
            "    IsStringRange     = %u,\n"
            "    IsDesignatorRange = %u,\n"
            "    IsAbsolute        = %u,\n"
            "    HasNull           = %u,\n"
            "    BitSize           = %u,\n"
            "    ReportCount       = %u,\n"
            "    UnitsExp          = 0x%02x,\n"
            "    Units             = 0x%02x,\n"
            "    LogicalMin        = %d,\n"
            "    LogicalMax        = %d,\n"
            "    PhysicalMin       = %d,\n"
            "    PhysicalMax       = %d,\n",
            value_caps[i].UsagePage,
            value_caps[i].ReportID,
            value_caps[i].IsAlias,
            value_caps[i].BitField,
            value_caps[i].LinkCollection,
            value_caps[i].LinkUsage,
            value_caps[i].LinkUsagePage,
            value_caps[i].IsRange,
            value_caps[i].IsStringRange,
            value_caps[i].IsDesignatorRange,
            value_caps[i].IsAbsolute,
            value_caps[i].HasNull,
            value_caps[i].BitSize,
            value_caps[i].ReportCount,
            (bt_i32)value_caps[i].UnitsExp,
            (bt_i32)value_caps[i].Units,
            (bt_i32)value_caps[i].LogicalMin,
            (bt_i32)value_caps[i].LogicalMax,
            (bt_i32)value_caps[i].PhysicalMin,
            (bt_i32)value_caps[i].PhysicalMax
        );

        if (value_caps[i].IsRange) {
            printf(
                "    Range = {\n"
                "        UsageMin     = 0x%02x,\n"
                "        UsageMax     = 0x%02x,\n"
                "        DataIndexMin = %u,\n"
                "        DataIndexMax = %u,\n",
                value_caps[i].Range.UsageMin,
                value_caps[i].Range.UsageMax,
                value_caps[i].Range.DataIndexMin,
                value_caps[i].Range.DataIndexMax
            );
        } else {
            printf(
                "    NotRange = {\n"
                "        Usage     = 0x%02x,\n"
                "        DataIndex = %u,\n",
                value_caps[i].NotRange.Usage,
                value_caps[i].NotRange.DataIndex
            );
        }
        printf(
            "    }\n"
            "}\n"
        );
    }
#endif

    bt_i8 x_found = 0, y_found = 0;
    bt_i8 id_found = 0, count_found = 0, time_found = 0;
    bt_u32 x_idx = 0, y_idx = 0, time_idx = 0;

    for (bt_u16 i = 0; i < num_value_caps; i++) {
        // Digitizers Usage Page
        if (value_caps[i].UsagePage == 0x0d) {
            // Contact ID Usage
            if (value_caps[i].NotRange.Usage == 0x51) {
                if (_bt_valid_value_cap(&value_caps[i])) {
                    id_found = 1;

                    bt_u32 idx = context->num_link_collections++;
                    context->link_collections[idx] =
                        value_caps[i].LinkCollection;
                } else {
                    context->err_str =
                        _BT_ERROR("Unsupported contact id value capabilities");
                    goto value_cap_err;
                }
            }

            // Scan Time Usage
            if (value_caps[i].NotRange.Usage == 0x56) {
                if (
                    _bt_valid_value_cap(&value_caps[i]) &&
                    // Note(Ian)
                    // Scan Time should be unsigned
                    // https://www.usb.org/sites/default/files/hid1_11.pdf
                    // "If both the Logical Minimum and Logical Maximum extents
                    // are defined as positive values (0 or greater) then the
                    // report field can be assumed to be an unsigned value."
                    value_caps[i].LogicalMin >= 0 && 
                    value_caps[i].LogicalMax >= 0 &&
                    ((value_caps[i].Units >> 12) & 0xf) == 0x1
                ) {
                    time_found = 1;
                    time_idx = i;
                } else {
                    context->err_str = _BT_ERROR(
                        "Unsupported scan time value capabilities"
                    );
                    goto value_cap_err;
                }
            }

            // Contact Count Usage
            if (value_caps[i].NotRange.Usage == 0x54) {
                if (
                    _bt_valid_value_cap(&value_caps[i]) &&
                    // Contact Count should be unsigned
                    value_caps[i].LogicalMin >= 0 && 
                    value_caps[i].LogicalMax >= 0
                ) {
                    count_found = 1;
                } else {
                    context->err_str = _BT_ERROR(
                        "Unsupported contact count value capabilities"
                                                 );
                    goto value_cap_err;
                }
            }
        }

        // Generic Desktop Usage Page
        if (value_caps[i].UsagePage == 0x01) {
            // X Usage
            if (value_caps[i].NotRange.Usage == 0x30) {
                if (_bt_valid_value_cap(&value_caps[i])) {
                    x_found = 1;
                    x_idx = i;
                } else {
                    context->err_str =
                        _BT_ERROR("Unsupported x value capabilities");
                    goto value_cap_err;
                }
            }

            // Y Usage
            if (value_caps[i].NotRange.Usage == 0x31) {
                if (_bt_valid_value_cap(&value_caps[i])) {
                    y_found = 1;
                    y_idx = i;
                } else {
                    context->err_str =
                        _BT_ERROR("Unsupported y value capabilities");
                    goto value_cap_err;
                }
            }
        }

        continue;

    value_cap_err:

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(value_caps);
        BT_FREE(context->link_collections);
        BT_FREE(context->rawinput);
        BT_FREE(context->ppd);
#endif

        return;
    }


    if (!x_found || !y_found || !id_found || !count_found || !time_found) {
        context->err_str = _BT_ERROR("Unable to find basic values");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(value_caps);
        BT_FREE(context->link_collections);
        BT_FREE(context->rawinput);
        BT_FREE(context->ppd);
#endif

        return;
    }

    context->x_min_logical = (bt_i16)value_caps[x_idx].LogicalMin;
    context->x_max_logical = (bt_i16)value_caps[x_idx].LogicalMax;
    context->y_min_logical = (bt_i16)value_caps[y_idx].LogicalMin;
    context->y_max_logical = (bt_i16)value_caps[y_idx].LogicalMax;

    context->x_min_mm = (bt_i16)value_caps[x_idx].PhysicalMin;
    context->x_max_mm = (bt_i16)value_caps[x_idx].PhysicalMax;
    context->y_min_mm = (bt_i16)value_caps[y_idx].PhysicalMin;
    context->y_max_mm = (bt_i16)value_caps[y_idx].PhysicalMax;

    // Note(Ian)
    // Physical min and max defaults
    // Page 47
    // https://www.usb.org/sites/default/files/hid1_11.pdf
    // "If both the Physical Minimum and Physical Maximum extents are equal to
    // 0 then they will revert to their default interpretation.""
    if (context->x_min_mm == 0 && context->x_max_mm == 0) {
        context->x_min_mm = context->x_min_logical;
        context->x_max_mm = context->x_max_logical;
    }
    if (context->y_min_mm == 0 && context->y_max_mm == 0) {
        context->y_min_mm = context->y_min_logical;
        context->y_max_mm = context->y_max_logical;
    }

    bt_u16 x_units = (bt_u16)value_caps[x_idx].Units;
    bt_u16 x_units_exp = (bt_u16)value_caps[x_idx].UnitsExp;
    bt_u16 y_units = (bt_u16)value_caps[y_idx].Units;
    bt_u16 y_units_exp = (bt_u16)value_caps[y_idx].UnitsExp;

    if (
        !_bt_to_mm(x_units, x_units_exp, &context->x_min_mm) ||
        !_bt_to_mm(x_units, x_units_exp, &context->x_max_mm) ||
        !_bt_to_mm(y_units, y_units_exp, &context->y_min_mm) ||
        !_bt_to_mm(y_units, y_units_exp, &context->y_max_mm)
    ) {
        context->err_str = _BT_ERROR("Invalid x and/or y physical units");

#ifdef BT_USE_ARENAS
        BT_ARENA_POP_TO(arena, init_pos);
#else
        BT_FREE(value_caps);
        BT_FREE(context->link_collections);
        BT_FREE(context->rawinput);
        BT_FREE(context->ppd);
#endif

        return;
    }

    // Note(Ian)
    // This calculation (and subsequent gesture deadzone calculations) assume
    // that the logical units in x and the logical units in y are at the same
    // scale relative to millimeters. I do not see why any hardware would work
    // differently, but if you run into an issue here, let me know.
    bt_f32 mm_to_logical = (bt_f32)(context->x_max_logical - context->x_min_mm) /
        (bt_f32)(context->x_max_mm - context->x_min_mm);

    bt_f32 pan_deadzone = desc->pan_deadzone_mm != 0.0f ? desc->pan_deadzone_mm : 2.0f;
    bt_f32 zoom_deadzone = desc->zoom_deadzone_mm != 0.0f ? desc->zoom_deadzone_mm : 12.0f;

    pan_deadzone *= mm_to_logical;
    zoom_deadzone *= mm_to_logical;

    context->pan_sqr_deadzone = pan_deadzone * pan_deadzone;
    context->zoom_sqr_deadzone = zoom_deadzone * zoom_deadzone;

    context->scan_time_exp = (bt_unit_exp)value_caps[time_idx].UnitsExp;

#ifdef BT_USE_ARENAS
    BT_ARENA_POP_TO(arena, pre_value_caps_pos);
#else
    BT_FREE(value_caps);
#endif


    context->initialized = 1;
}

void bt_process_input(
    bt_context* context, HWND hWnd, WPARAM wParam, LPARAM lParam
) {
    (void)wParam;

    if (!context->has_trackpad || !context->initialized) { return; }

    RAWINPUTHEADER header = { 0 };
    bt_u32 size = sizeof(RAWINPUTHEADER);

    if (
        GetRawInputData(
            (HRAWINPUT)lParam, RID_HEADER, &header,
            &size, sizeof(RAWINPUTHEADER)
        ) != sizeof(RAWINPUTHEADER)
    ) {
        context->err_str = _BT_ERROR("Failed to get RAWINPUTHEADER");
        return;
    }

    if (
        header.hDevice != context->device_handle ||
        header.dwSize > context->rawinput_size
    ) {
        return; 
    }

    size = context->rawinput_size;

    if (
        GetRawInputData(
            (HRAWINPUT)lParam, RID_INPUT, context->rawinput,
            &size, sizeof(RAWINPUTHEADER)
        ) != header.dwSize
    ) {
        context->err_str = _BT_ERROR("Failed to get RAWINPUT data");
        goto end;
    }

    bt_u32 num_contacts_seen = 0;
    bt_i16 contact_ids[BT_MAX_CONTACTS] = { 0 };
    bt_i16 contact_xs[BT_MAX_CONTACTS] = { 0 };
    bt_i16 contact_ys[BT_MAX_CONTACTS] = { 0 };

    PCHAR report = (PCHAR)context->rawinput->data.hid.bRawData;
    bt_u32 report_length = context->rawinput->data.hid.dwSizeHid;

    ULONG contact_count = 0;
    if (
        HidP_GetUsageValue(
            HidP_Input, 0x0d, 0, 0x54, &contact_count,
            context->ppd, report, report_length
        ) != HIDP_STATUS_SUCCESS
    ) {
        context->err_str = _BT_ERROR("Failed to get contact count");
        goto end;
    }

    ULONG scan_time = 0;
    if (
        HidP_GetUsageValue(
            HidP_Input, 0x0d, 0, 0x56, &scan_time,
            context->ppd, report, report_length
        ) != HIDP_STATUS_SUCCESS
    ) {
        context->err_str = _BT_ERROR("Failed to get scan time");
        goto end;
    }

    bt_sample sample = {
        .contact_count = (bt_u16)contact_count,
        .scan_time = (bt_u16)scan_time
    };

    WPARAM outgoing_wparam =
        ((bt_u64)sample.contact_count << 16) | 
        ((bt_u64)sample.scan_time     <<  0);

    for (
        bt_u32 i = 0;
        i < context->num_link_collections &&
        num_contacts_seen < contact_count;
        i++
    ) {
        ULONG id = 0, x = 0, y = 0;
        bt_u16 lc = context->link_collections[i];

        if (
            HidP_GetUsageValue(
                HidP_Input, 0x0d, lc, 0x51, &id,
                context->ppd, report, report_length
            ) != HIDP_STATUS_SUCCESS
        ) {
            context->err_str =
                _BT_ERROR("Failed to get contact id usage value");
            goto end;
        }

        bt_i8 seen_contact = 0;
        for (bt_u32 j = 0; j < num_contacts_seen; j++) {
            if (contact_ids[j] == (bt_u16)id) {
                seen_contact = 1;
                break;
            }
        }

        if (seen_contact) { continue; }

        if (num_contacts_seen >= BT_MAX_CONTACTS) {
            context->err_str = _BT_ERROR(
                "Ran out of contacts (try increasing BT_MAX_CONTACTS)"
            );
            goto end;
        }

        contact_ids[num_contacts_seen++] = (bt_i16)id;

        if (
            HidP_GetUsageValue(
                HidP_Input, 0x01, lc, 0x30, &x,
                context->ppd, report, report_length
            ) != HIDP_STATUS_SUCCESS ||
            HidP_GetUsageValue(
                HidP_Input, 0x01, lc, 0x31, &y,
                context->ppd, report, report_length
            ) != HIDP_STATUS_SUCCESS
        ) {
            context->err_str = _BT_ERROR("Failed to get contact x and/or y");
            goto end;
        }

        contact_xs[num_contacts_seen - 1] = (bt_i16)x;
        contact_ys[num_contacts_seen - 1] = (bt_i16)y;

        bt_u64 outgoing_lparam = 
            ((bt_u64)id << 32) |
            ((bt_u64)y  << 16) |
            ((bt_u64)x  <<  0);

        if (!context->flags.disable_raw_msgs) {
            SendMessage(hWnd, BT_MSG_RAW, outgoing_wparam, outgoing_lparam);
        }
    }

    if (!context->flags.disable_contact_msgs) {
        // Remove contacts that are no longer active from state
        for (bt_i32 i = 0; i < (bt_i32)context->num_contacts; i++) {
            bt_i8 active = 0;

            for (bt_u32 j = 0; j < contact_count; j++) {
                if (context->contacts[i].id == contact_ids[j]) {
                    active = 1;
                    break;
                }
            }

            if (active) { continue; }

            if (!context->flags.disable_contact_msgs) {
                bt_u64 outgoing_lparam = _BT_CONTACT_TO_LPARAM(context->contacts[i]);

                SendMessage(hWnd, BT_MSG_CONTACT_EXIT, 0, outgoing_lparam);
            }

            for (bt_u32 j = (bt_u32)i; j < context->num_contacts - 1; j++) {
                context->contacts[j] = context->contacts[j + 1];
            }

            context->num_contacts--;
            i--;
        }

        // Check for new contacts and update existing ones
        for (bt_u32 i = 0; i < contact_count; i++) {
            bt_i32 same_id_idx = -1;

            for (bt_u32 j = 0; j < context->num_contacts; j++) {
                if (contact_ids[i] == context->contacts[j].id) {
                    same_id_idx = (bt_i32)j;
                }
            }

            if (same_id_idx == -1) {
                if (context->num_contacts >= BT_MAX_CONTACTS) {
                    context->err_str = _BT_ERROR(
                        "Ran out of contacts. Try increasing BT_MAX_CONTACTS"
                    );
                } else {
                    context->contacts[context->num_contacts++] = (bt_contact){
                        .id = contact_ids[i],
                        .x = contact_xs[i],
                        .y = contact_ys[i],
                    };

                    if (!context->flags.disable_contact_msgs) {
                        bt_u64 outgoing_lparam = _BT_CONTACT_TO_LPARAM(
                            context->contacts[context->num_contacts-1]
                        );

                        SendMessage(hWnd, BT_MSG_CONTACT_ENTER, 0, outgoing_lparam);
                    }
                }
            } else {
                // Same id found
                bt_contact* contact = &context->contacts[same_id_idx];

                if (contact->x != contact_xs[i] || contact->y != contact_ys[i]) {
                    contact->x = contact_xs[i];
                    contact->y = contact_ys[i];

                    if (!context->flags.disable_contact_msgs) {
                        bt_u64 outgoing_lparam = _BT_CONTACT_TO_LPARAM(*contact);
                        SendMessage(hWnd, BT_MSG_CONTACT_UPDATE, 0, outgoing_lparam);
                    }
                }
            }
        }
    }

    if (!context->flags.disable_gesture_msgs) {
        if (contact_count != 2) {
            context->gesture_state = BT_GES_NONE;
            goto end;
        }

        if (context->gesture_state == BT_GES_NONE) { 
            context->gesture_state = BT_GES_UNDECIDED;

            context->ges_start_x0 = contact_xs[0];
            context->ges_start_y0 = contact_ys[0];
            context->ges_start_x1 = contact_xs[1];
            context->ges_start_y1 = contact_ys[1];
        }

        bt_u8 prev_state = context->gesture_state;

        // Check for pan gesture
        if (context->gesture_state == BT_GES_UNDECIDED) {
            // Contact midpoints
            bt_i16 start_x = (context->ges_start_x0 + context->ges_start_x1) / 2;
            bt_i16 start_y = (context->ges_start_y0 + context->ges_start_y1) / 2;
            bt_i16 cur_x = (contact_xs[0] + contact_xs[1]) / 2;
            bt_i16 cur_y = (contact_ys[0] + contact_ys[1]) / 2;

            bt_f32 sqr_dist = _bt_sqr_dist(start_x, start_y, cur_x, cur_y);
            
            if (sqr_dist > context->pan_sqr_deadzone) {
                context->gesture_state = BT_GES_PAN;
            }
        }

        // Check for zoom gesture
        if (context->gesture_state == BT_GES_UNDECIDED) {
            bt_f32 start_sqr_dist = _bt_sqr_dist(
                context->ges_start_x0, context->ges_start_y0, 
                context->ges_start_x1, context->ges_start_y1 
            );

            bt_f32 cur_sqr_dist = _bt_sqr_dist(
                contact_xs[0], contact_ys[0], 
                contact_xs[1], contact_ys[1] 
            );
            
            bt_f32 sqr_dist_change = _BT_ABS(cur_sqr_dist - start_sqr_dist);

            if (sqr_dist_change > context->zoom_sqr_deadzone) {
                context->gesture_state = BT_GES_ZOOM;
            }
        }

        if (context->gesture_state != BT_GES_UNDECIDED) {
            if (prev_state == BT_GES_UNDECIDED) {
                context->ges_prev_x0 = context->ges_start_x0;
                context->ges_prev_y0 = context->ges_start_y0;
                context->ges_prev_x1 = context->ges_start_x1;
                context->ges_prev_y1 = context->ges_start_y1;
            }

            // Skipping over inputs where nothing moved
            if (
                contact_xs[0] == context->ges_prev_x0 && 
                contact_ys[0] == context->ges_prev_y0 && 
                contact_xs[1] == context->ges_prev_x1 && 
                contact_ys[1] == context->ges_prev_y1 
            ) {
                goto end;
            }
        }

        if (context->gesture_state == BT_GES_PAN) {
            bt_f32 prev_x = (bt_f32)(context->ges_prev_x0 + context->ges_prev_x1) / 2;
            bt_f32 prev_y = (bt_f32)(context->ges_prev_y0 + context->ges_prev_y1) / 2;
            bt_f32 cur_x = (bt_f32)(contact_xs[0] + contact_xs[1]) / 2;
            bt_f32 cur_y = (bt_f32)(contact_ys[0] + contact_ys[1]) / 2;

            bt_gesture_pan pan = {
                .move_x = cur_x - prev_x,
                .move_y = cur_y - prev_y
            };

            bt_u64 outgoing_lparam = pan.bits;

            // `outgoing_wparam` contains the `bt_sample` from this input message
            SendMessage(hWnd, BT_MSG_GESTURE_PAN, outgoing_wparam, outgoing_lparam);
        }

        if (context->gesture_state == BT_GES_ZOOM) {
            bt_f32 start_dist = _bt_dist(
                context->ges_start_x0, context->ges_start_y0, 
                context->ges_start_x1, context->ges_start_y1 
            );
            bt_f32 prev_dist = _bt_dist(
                context->ges_prev_x0, context->ges_prev_y0, 
                context->ges_prev_x1, context->ges_prev_y1 
            );
            bt_f32 cur_dist = _bt_dist(
                contact_xs[0], contact_ys[0],
                contact_xs[1], contact_ys[1]
            );

            bt_f32 dist_change = cur_dist - prev_dist;

            bt_gesture_zoom zoom = {
                .start_dist = start_dist,
                .dist_change = dist_change
            };

            bt_u64 outgoing_lparam = zoom.bits;
            // `outgoing_wparam` contains the `bt_sample` from this input message
            SendMessage(hWnd, BT_MSG_GESTURE_ZOOM, outgoing_wparam, outgoing_lparam);
        }

        if (context->gesture_state != BT_GES_UNDECIDED) {
            context->ges_prev_x0 = contact_xs[0];
            context->ges_prev_y0 = contact_ys[0];
            context->ges_prev_x1 = contact_xs[1];
            context->ges_prev_y1 = contact_ys[1];
        }
    }

end:
    context->prev_input_us = _bt_time_us(context);
}

void bt_passive_update(bt_context* context, HWND hWnd) {
    if (!context->has_trackpad || !context->initialized) { return; }
    if (context->num_contacts == 0) { return; }

    bt_u64 cur_time_us = _bt_time_us(context);

    if ((cur_time_us - context->prev_input_us) >= context->exit_timeout_us) {
        if (!context->flags.disable_contact_msgs) {
            for (bt_i32 i = (bt_i32)context->num_contacts - 1; i >= 0; i--) {
                bt_u64 outgoing_lparam = _BT_CONTACT_TO_LPARAM(context->contacts[i]);
                SendMessage(hWnd, BT_MSG_CONTACT_EXIT, 0, outgoing_lparam);
            }
        }

        context->gesture_state = BT_GES_NONE;
        context->num_contacts = 0;
    }
}

void bt_destroy(bt_context* context) {
#ifdef BT_USE_ARENAS
    (void)context;
#else
    BT_FREE(context->ppd);
    BT_FREE(context->rawinput);
    BT_FREE(context->link_collections);
#endif
}

// Note(Ian)
// Currently, all the values are designed to be 16 bit, not ranges,
// and not arrays. I am not sure if there are devices where certain
// values (namely Scan Time) do have a greater bit width. If you do
// run into this, please make an issue on GitHub
static bt_i32 _bt_valid_value_cap(HIDP_VALUE_CAPS* value_cap) {
    return
        !value_cap->IsRange &&
        value_cap->BitSize <= 16 &&
        value_cap->ReportCount == 1;
}

/* Note(Ian)
The USB HID unit system confused me for a long time,
so here is my attempt at an explanation:

The Unit system is described on pages 37-39 of 
"Device Class Definition for Human Interface Devices (HID)"
(https://www.usb.org/sites/default/files/hid1_11.pdf)

The Unit number itself is a 16 bit integer, where each nibble encodes 
different information. Nibble 0 defines which system of units should be used.
For example if (Unit & 0xf) == 0x1, that specifies this unit should use SI
linear units. Nibbles 1 through 6 define both which units to include, and 
their exponents. THESE NIBBLES CANNOT CHANGE WHICH SYSTEM OF UNITS ARE USED.
That is the part that confused me. If the first nibble is 1, the length unit
is centimeter regardless of the value of the length nibble (unless it is zero).
Additionally, these nibbles say nothing about the magnitude of the units, only
their exopnent. This is also confusing because the same table is used for
the Unit Exponent value. The final unit's magnitude is multiplied by 10 to
the Unit Exponent.

As such, when converting the x and y bounds to millimeters, I am only 
taking units values that are length based (SI or English) and with an 
exponent of 1 (measuring length, not area)
*/
static bt_i32 _bt_to_mm(bt_u16 units, bt_u16 units_exp, bt_f32* val) {
    if (
        // Unit System must be SI Linear or English Linear
        ((units & 0xf) != 0x1 && (units & 0xf) != 0x3) ||
        // Length exponent must be 1 (not measuring area, volume, etc.) 
        ((units >> 4) & 0xf) != 0x1 || 
        units_exp > 0xf
    ) {
        return 0;
    }

    static const bt_f32 multipliers[] = {
        // Centimeters to mm
        1e1f, 1e2f, 1e3f, 1e4f, 1e5f, 1e6f, 1e7f,
        1e8f, 1e-7f, 1e-6f, 1e-5f, 1e-4f, 1e-3f,
        1e-2f, 1e-1f, 1e0f
    };

    *val *= multipliers[units_exp];

    // Units are in inches
    if ((units & 0xf) == 0x3) {
        *val *= 2.54f;
    }

    return 1;
}

static bt_u64 _bt_time_us(bt_context* context) {
    LARGE_INTEGER ticks = { 0 };

    if (!QueryPerformanceCounter(&ticks)) {
        context->err_str = _BT_ERROR("Failed to query performance counter");
        return 0;
    }
    
    return (bt_u64)ticks.QuadPart * 1000000 / context->perf_freq;
}

static bt_f32 _bt_sqr_dist(bt_i16 x0, bt_i16 y0, bt_i16 x1, bt_i16 y1) {
    bt_f32 x_diff = (bt_f32)x1 - x0;
    bt_f32 y_diff = (bt_f32)y1 - y0;

    return (x_diff * x_diff + y_diff * y_diff);
}

static bt_f32 _bt_dist(bt_i16 x0, bt_i16 y0, bt_i16 x1, bt_i16 y1) {
    bt_f32 x_diff = (bt_f32)x1 - x0;
    bt_f32 y_diff = (bt_f32)y1 - y0;

    //return sqrtf((bt_f32)(x_diff * x_diff + y_diff * y_diff));
    return 0;
}

#endif // BT_IMPLEMENTATION

/*
MIT License

Copyright (c) 2026 Ian Dvorin

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

